export const LOANS = [
  {
    icon: "🏠",
    iconBg: "#e8f0fe",
    rate: "8.5% p.a.",
    rateColor: "#2771e2",
    title: "Home Loan",
    desc: "Finance the purchase of a ready-to-move or under-construction residential property.",
    maxAmount: "₹5 Cr",
    tenure: "30 yrs",
    approval: "48 hrs",
    features: [
      "Salaried & self-employed eligible",
      "Tax benefit under Sec 80C & 24B",
      "Up to 90% of property value funded",
    ],
    applyLabel: "Apply for home loan",
    loanKey: "PURCHASE",
  },
  {
    icon: "🏗️",
    iconBg: "#e6f9f0",
    rate: "9.0% p.a.",
    rateColor: "#2771e2",
    title: "Plot Loan",
    desc: "Purchase a residential plot to build your dream home at your own pace.",
    maxAmount: "₹3 Cr",
    tenure: "20 yrs",
    approval: "72 hrs",
    features: [
      "Up to 75% of plot value funded",
      "DTCP / HMDA approved plots only",
      "Top-up available for construction",
    ],
    applyLabel: "Apply for plot loan",
    loanKey: "CONSTRUCTION",
  },
  {
    icon: "🔧",
    iconBg: "#fff7ed",
    rate: "9.5% p.a.",
    rateColor: "#2771e2",
    title: "Home Renovation Loan",
    desc: "Upgrade, repair or remodel your existing home with a quick and simple loan.",
    maxAmount: "₹50L",
    tenure: "15 yrs",
    approval: "24 hrs",
    features: [
      "No collateral up to ₹10L",
      "Covers flooring, plumbing, electrical",
      "Minimal documentation required",
    ],
    applyLabel: "Apply for renovation loan",
    loanKey: "PURCHASE",
  },
  {
    icon: "🌐",
    iconBg: "#f3f0ff",
    rate: "8.8% p.a.",
    rateColor: "#2771e2",
    title: "NRI Home Loan",
    desc: "Specially designed for Non-Resident Indians to invest in property back home.",
    maxAmount: "₹5 Cr",
    tenure: "25 yrs",
    approval: "5 days",
    features: [
      "NRE / NRO account repayment",
      "Power of attorney accepted",
      "FEMA compliant, online process",
    ],
    applyLabel: "Apply for NRI loan",
    loanKey: "PURCHASE",
  },
];